IDSM/Controllers/LoggingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDSM.Repository;
using IDSM.ViewModels;
using IDSM.Helpers;
using IDSM.Logging.Repository;
using IDSM.Logging.Helpers;
using IDSM.Logging.Services.Paging;
using System.ServiceModel.Syndication;
using IDSM.Logging;
using IDSM.Logging.Services.RSS;
using IDSM.Logging.Services.Charting.Google.Visualisation;

namespace IDSM.Controllers
{
        [Authorize]
        public class LoggingController : Controller
        {
            private readonly LogReportingFacade loggingRepository;

            public LoggingController()
            {
                loggingRepository = new LogReportingFacade();
            }

            public LoggingController(LogReportingFacade repository)
            {
                loggingRepository = repository;
            }

            /// <summary>
            /// Returns the Index view
            /// </summary>
            /// <param name="Period">Text representation of the date time period. eg: Today, Yesterday, Last Week etc.</param>
            /// <param name="LoggerProviderName">Elmah, Log4Net, NLog, Health Monitoring etc</param>
            /// <param name="LogLevel">Debug, Info, Warning, Error, Fatal</param>
            /// <param name="page">The current page index (0 based)</param>
            /// <param name="PageSize">The number of records per page</param>
            /// <returns></returns>
            public ActionResult Index(string Period, string LoggerProviderName, string LogLevel, int? page, int? PageSize)
            {
                // Set up our default values
                string defaultPeriod = Session["Period"] == null ? "Today" : Session["Period"].ToString();
                string defaultLogType = Session["LoggerProviderName"] == null ? "All" : Session["LoggerProviderName"].ToString();
                string defaultLogLevel = Session["LogLevel"] == null ? "Error" : Session["LogLevel"].ToString();

                // Set up our view model
                LoggingIndexModel model = new LoggingIndexModel();

                model.Period = (Period == null) ? defaultPeriod : Period;
                model.LoggerProviderName = (LoggerProviderName == null) ? defaultLogType : LoggerProviderName;
                model.LogLevel = (LogLevel == null) ? defaultLogLevel : LogLevel;
                model.CurrentPageIndex = page.HasValue ? page.Value - 1 : 0;
                model.PageSize = PageSize.HasValue ? PageSize.Value : 20;

                TimePeriod timePeriod = TimePeriodHelper.GetUtcTimePeriod(model.Period);

                // Grab the data from the database
                model.LogEvents = loggingRepository.GetByDateRangeAndType(model.CurrentPageIndex, model.PageSize, timePeriod.Start, timePeriod.End, model.LoggerProviderName, model.LogLevel);

                // Put this into the ViewModel so our Pager can get at these values
                ViewData["Period"] = model.Period;
                ViewData["LoggerProviderName"] = model.LoggerProviderName;
                ViewData["LogLevel"] = model.LogLevel;
                ViewData["PageSize"] = model.PageSize;

                // Put the info into the Session so that when we browse away from the page and come back that the last settings are rememberd and used.
                Session["Period"] = model.Period;
                Session["LoggerProviderName"] = model.LoggerProviderName;
                Session["LogLevel"] = model.LogLevel;

                return View(model);
            }

            //
            // GET: /Logging/Details/5

            public ActionResult Details(string loggerProviderName, string id)
            {
                LogEvent logEvent = loggingRepository.GetById(loggerProviderName, id);

                return View(logEvent);
            }

            // string Period, string LoggerProviderName, string LogLevel, int? page, int? PageSize
            public ActionResult Search()
            {
                return View();
            }

            /// <summary>
            /// 
            /// </summary>
            /// <param name="Period"></param>
            /// <param name="LoggerProviderName"></param>
            /// <param name="LogLevel"></param>
            /// <returns></returns>
            public JsonResult ChartData(string Period, string LoggerProviderName, string LogLevel)
            {
                if (Period == "Today" || Period == "Yesterday")
                {
                    return ChartDataByHour(Period, LoggerProviderName, LogLevel);
                }
                else
                {
                    return ChartDataByDay(Period, LoggerProviderName, LogLevel);
                }
            }

            /// <summary>
            /// 
            /// </summary>
            /// <param name="Period"></param>
            /// <param name="LoggerProviderName"></param>
            /// <param name="logLevel"></param>
            /// <returns></returns>
            public JsonResult ChartDataByHour(string Period, string LoggerProviderName, string logLevel)
            {
                Func<LogEvent, Object> groupByClause = c => c.LogDate.ToLocalTime().Hour;

                return ChartDataByTimePeriod(Period, LoggerProviderName, logLevel, "", groupByClause);
            }

            /// <summary>
            /// 
            /// </summary>
            /// <param name="Period"></param>
            /// <param name="LoggerProviderName"></param>
            /// <param name="logLevel"></param>
            /// <returns></returns>
            public JsonResult ChartDataByDay(string Period, string LoggerProviderName, string logLevel)
            {
                Func<LogEvent, Object> groupByClause = c => c.LogDate.ToLocalTime().Date;

                return ChartDataByTimePeriod(Period, LoggerProviderName, logLevel, "dd/MM/yyyy", groupByClause);
            }

            /// <summary>
            /// 
            /// </summary>
            /// <param name="Period"></param>
            /// <param name="LoggerProviderName"></param>
            /// <param name="logLevel"></param>
            /// <param name="keyFormatString"></param>
            /// <param name="groupByClause"></param>
            /// <returns></returns>
            public JsonResult ChartDataByTimePeriod(string Period, string LoggerProviderName, string logLevel, string keyFormatString, Func<LogEvent, Object> groupByClause)
            {
                TimePeriod timePeriod = TimePeriodHelper.GetUtcTimePeriod(Period);

                // Grab ALL entries for the chart (DO NOT PAGE REPORTING DATA!!!)
                IPagedList<LogEvent> chartEntries = loggingRepository.GetByDateRangeAndType(0, Int32.MaxValue, timePeriod.Start, timePeriod.End, LoggerProviderName, logLevel);

                var groupedByDate = chartEntries.GroupBy(groupByClause).OrderBy(y => y.Key);

                var groupedByDateAndThenName = groupedByDate.Select(group => new { Key = group.Key, NestedGroup = group.ToLookup(result => result.LoggerProviderName, result => result.Id) });

                var LoggerNames = (from logEvent in chartEntries
                                   select new { Name = logEvent.LoggerProviderName }
                                   ).Distinct().OrderBy(item => item.Name);

                ChartData chartData = new ChartData();

                // Add columns
                chartData.AddColumn(new ChartColumn("0", "Period", "string"));
                int columnIndex = 1;
                foreach (var name in LoggerNames)
                {
                    chartData.AddColumn(new ChartColumn(columnIndex.ToString(), name.Name.ToString(), "number"));
                    columnIndex++;
                }

                // add row data
                foreach (var myDate in groupedByDateAndThenName)
                {
                    ChartRow row = new ChartRow();

                    string dateString = (myDate.Key is DateTime) ? ((DateTime)myDate.Key).ToString(keyFormatString) : myDate.Key.ToString();
                    row.AddCellItem(new ChartCellItem(dateString, ""));

                    foreach (var name in LoggerNames)
                    {
                        bool valueFound = false;
                        foreach (var myLogger in myDate.NestedGroup)
                        {
                            if (myLogger.Key == name.Name.ToString())
                            {
                                row.AddCellItem(new ChartCellItem(myLogger.Count(), ""));
                                valueFound = true;
                            }
                        }
                        if (!valueFound) row.AddCellItem(new ChartCellItem(0, ""));
                    }

                    chartData.AddRow(row);
                }

                return Json(chartData, "text/x-json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
            }

            /// <summary>
            /// Gets the chart
            /// </summary>
            /// <param name="Period"></param>
            /// <param name="LoggerProviderName"></param>
            /// <param name="LogLevel"></param>
            /// <returns></returns>
            public ActionResult Chart(string Period, string LoggerProviderName, string LogLevel)
            {
                string defaultPeriod = Session["Period"] == null ? "Today" : Session["Period"].ToString();
                string defaultLoggerProviderName = Session["LoggerProviderName"] == null ? "All" : Session["LoggerProviderName"].ToString();
                string defaultLogLevel = Session["LogLevel"] == null ? "Error" : Session["LogLevel"].ToString();

                LoggingIndexModel model = new LoggingIndexModel();

                model.Period = (Period == null) ? defaultPeriod : Period;
                model.LoggerProviderName = (LoggerProviderName == null) ? defaultLoggerProviderName : LoggerProviderName;

IDSM/Views/Logging/Chart.cshtml
@model IDSM.ViewModels.LoggingIndexModel
@using IDSM.Logging;
@using IDSM.Logging.Helpers;
@using IDSM.Logging.Services.Paging;
@{
    ViewBag.Title = "Chart";
}

<h2>Chart</h2>
    @using (Html.BeginForm("Chart", "Logging", FormMethod.Get, new { id = "myform" }))
       {

    <div class="grid-options">
        View : 
        @Html.ActionLink("List", "Index")
        | <strong>Chart</strong>
        | @Html.ActionLink("RSS", "RssFeed", new { LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel }, new { target = "_blank" })        
    </div>  

    <div class="grid-filter">        
        <div class="inner">

        Logger : @Html.DropDownList("LoggerProviderName", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogProviderNames, "Value", "Text"))  

        Level : @Html.DropDownList("LogLevel", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogLevels, "Value", "Text"))  

        For : @Html.DropDownList("Period", new SelectList(IDSM.Logging.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))  
        
        <input id="btnGo" name="btnGo" type="submit" value="Apply Filter" />                      

        </div>
    </div>

    }

    <script type="text/javascript" src="http://www.google.com/jsapi"></script>

    <script type="text/javascript">

        // Load the Visualization API and the corechart package.
        google.load("visualization", "1", { packages: ["corechart"] });

        // Set a callback to run when the Google Visualization API is loaded.
        google.setOnLoadCallback(drawChart);

        function drawChart() {

            var loggerProviderName = $("#LoggerProviderName").val();
            var period = $("#Period").val();
            var logLevel = $("#LogLevel").val();            

            var actionUrl = "/Logging/ChartData";
            actionUrl += "?LoggerProviderName=" + loggerProviderName;
            actionUrl += "&Period=" + period;
            actionUrl += "&LogLevel=" + logLevel;

            // alert(actionUrl);

            var testJson = $.getJSON(actionUrl, function (chartdata) {

                var data = new google.visualization.DataTable();

                // column
                for (var col = 0; col < chartdata.cols.length; col++) {                    
                    data.addColumn(chartdata.cols[col].type, chartdata.cols[col].label);
                }                

                // row
                for (var row = 0; row < chartdata.rows.length; row++) {                    

                    data.addRow();

                    for (var col = 0; col < chartdata.cols.length; col++) {                        

                        var myRow = chartdata.rows[row];
                        var myCell = myRow.c[col];

                        data.setCell(row, col, myCell.v);                        
                    }
                }

                var options = { 'width': 750, 'height': 450, 'title': 'Logging' };                

                var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
                chart.draw(data, options);

            });

        }    

    </script>    

    <div id="chart_div"></div>

IDSM/Views/Logging/Details.cshtml
@{
    ViewBag.Title = "Details";
}

    <h2>Details</h2>

    <p>        
        @Html.ActionLink("Back to List", "Index") 
    </p>

    <fieldset>
        <legend>Fields</legend>
        
        <div class="display-label">Id</div>
        <div class="display-field">@Model.Id </div>
        
        <div class="display-label">LogDate</div>
        <div class="display-field">@String.Format("{0:g}", Model.LogDate) </div>
        
        <div class="display-label">Name</div>
        <div class="display-field">@Model.LoggerProviderName </div>
        
        <div class="display-label">Source</div>
        <div class="display-field">@Model.Source </div>
        
        <div class="display-label">MachineName</div>
        <div class="display-field">@Model.MachineName </div>
        
        <div class="display-label">Type</div>
        <div class="display-field">@Model.Type </div>
        
        <div class="display-label">Level</div>
        <div class="display-field">@Model.Level </div>
        
        <div class="display-label">Message</div>
        <div class="display-field">
            <pre>@Model.Message.WordWrap(80) </pre>
        </div>
        
        <div class="display-label">StackTrace</div>
        <div class="display-field">@Model.StackTrace </div>                      
        
    </fieldset>

    @IDSM.Logging.Helpers.FormsHelper.OutputXmlTableForLogging(Model.AllXml) 

    <p>        
        @Html.ActionLink("Back to List", "Index") 
    </p>

IDSM/Views/Logging/Index.cshtml
@model IDSM.ViewModels.LoggingIndexModel
@using IDSM.Logging;
@using IDSM.Logging.Helpers;
@using IDSM.Logging.Services.Paging;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
 View :
 <strong>List</strong>
 | @Html.ActionLink("Chart", "Chart")
 | @Html.ActionLink("RSS", "RssFeed", new { LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel }, new { target = "_blank" })
 </div>

@using (Html.BeginForm("Index", "Logging", new { page = 0 }, FormMethod.Get, new { id = "myform" }))
       {

<div>
 <div>
 
 Logger : @Html.DropDownList("LoggerProviderName", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogProviderNames, "Value", "Text"))
 
 Level : @Html.DropDownList("LogLevel", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogLevels, "Value", "Text"))
 
 For : @Html.DropDownList("Period", new SelectList(IDSM.Logging.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))
 
 <input id="btnGo" name="btnGo" type="submit" value="Apply Filter" />
 
 </div>
 </div>
    
    }

<div>
 
 <div>
 <div>
 
 <span style="float: left">
 @string.Format("{0} records found. Page {1} of {2}", Model.LogEvents.TotalItemCount, Model.LogEvents.PageNumber, Model.LogEvents.PageCount)
 </span>
 
 <span style="float: right">
 Show @Html.DropDownList("PageSize", new SelectList(IDSM.Logging.Helpers.FormsHelper.PagingPageSizes, "Value", "Text"), new { onchange = "document.getElementById('myform').submit()" }) results per page
 </span>
 
 <div style="clear: both"></div>
 
 </div>
 
 </div>
 
 <div>
 <div>
 @Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new { LogType = ViewData["LogType"], Period = ViewData["Period"], PageSize = ViewData["PageSize"] })
 </div>
 </div>
 
 </div>

@if (Model.LogEvents.Count() == 0) { 
 
 <p>No results found</p>
 
 } else { 
 
 <div>
 <table>
 <tr>
 <th></th>
 <th>
 #
 </th>
 <th>
 Log
 </th>
 <th>
 Date
 </th>
 <th style='white-space: nowrap;'>
 Time ago
 </th>
 <th>
 Host
 </th>
 <th>
 Source
 </th>
 <th>
 Message
 </th>
 <th>
 Type
 </th>
 <th>
 Level
 </th>
 </tr>
 
@{int i = 0;  
 foreach (var item in Model.LogEvents)
 { 
 <tr>
 <td>
 @Html.ActionLink("Details", "Details", new { id = item.Id.ToString(), loggerProviderName = item.LoggerProviderName })
 </td>
 <td>
 @i.ToString() 
 </td>
 <td>
 @item.LoggerProviderName
 </td>
 <td style='white-space: nowrap;'>
 @String.Format("{0:g}", item.LogDate.ToLocalTime())
 </td>
 <td style='white-space: nowrap;'>
 @item.LogDate.ToLocalTime().TimeAgoString()
 </td>
 <td>
 @item.MachineName
 </td>
 <td>
 @item.Source
 </td>
 <td>
 <pre>@item.Message.WordWrap(80) </pre>
 </td>
 <td>
 @item.Type
 </td>
 <td>
 @item.Level.ToLower().ToPascalCase() 
 </td>
 </tr>
}} 
 
 </table>
 </div>
} 
 
 <div>
 
 <div>
 <div>
 @Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new { LogType = ViewData["LogType"], Period = ViewData["Period"], PageSize = ViewData["PageSize"] })
 </div>
 </div>
 
 </div>

IDSM/Views/Logging/Manage.cshtml
@{
    ViewBag.Title = "Manage";
}

    <h2>Manage</h2>

    @ViewData["Message"] 

    @using (Html.BeginForm()) {

        <fieldset>
            <legend>Fields</legend>
            
            @Html.EditorForModel() 

            <p>
                <input type="submit" value="Clear Log" />
            </p>

        </fieldset>

    }

IDSM/Views/Logging/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>


<script type="text/javascript">
    $(function () {
        $('.datePicker').datepicker({
            dateFormat: "yy-mm-dd"
        });
    });
</script>

    <div class="grid-filter">        
        <div class="inner">

        <table>
            <tr>
                <td>Logger</td>
                <td>@Html.DropDownList("LoggerProviderName", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogProviderNames, "Value", "Text")) </td>
            </tr>
            <tr>
                <td>Level</td>
                <td>@Html.DropDownList("LogLevel", new SelectList(IDSM.Logging.Helpers.FormsHelper.LogLevels, "Value", "Text"))  </td>
            </tr>
            <tr>
                <td>For</td>
                <td>
                    <input type="radio" id="dateOption1" name="dateoption" /> @Html.DropDownList("Period", new SelectList(IDSM.Logging.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))                    
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="radio" id="dateOption2" name="dateoption" /> 
                    <input style="width: 85px;" class="datePicker" type="text" id="txtDateStart" name="txtDateStart" /> and <input style="width: 85px;" class="datePicker" type="text" id="txtDateEnd" name="txtDateEnd" />
                </td>
            </tr>
            <tr>
                <td>Search criteria</td>
                <td>
                    <textarea id="criteria" name="criteria" rows="3" cols="60"></textarea>
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right;">
                    <input id="btnGo" name="btnGo" type="submit" value="Search" />                      
                </td>
            </tr>
        </table>
        
        

        </div>
    </div>