IDSM/Controllers/GamesAdminController.cs
using IDSM.Model;
using System.Web.Mvc;
﻿using IDSM.Repository;
﻿using IDSM.ViewModel;
using IDSM.ServiceLayer;
using WebMatrix.WebData;

namespace IDSM.Controllers
{
    [Authorize]
    public class GamesAdminController : Controller
    {
        //IWebSecurityWrapper _wr;
        private readonly IService _service;

        /// <summary>
        /// Instantiates controller class. Service layer injected by Unity.
        /// </summary>
        /// <param name="service"></param>
        public GamesAdminController(IService service)
        {
            _service = service;
        }

        /// <summary>
        /// Displays 'Games Homepage' view - list of all active games, plus navigation to create new games & reset games 
        /// </summary>
        /// <returns></returns>
        public ViewResult Index()
        {
           // GameViewModel _gvm = new GameViewModel { Games = _service.GetAllGames() };
            GameViewModel _gvm = new GameViewModel { Games = _service.GetAllGamesUserParticipatesIn(WebSecurity.CurrentUserId) };
            return View(_gvm);
        }

        /// <summary>
        /// Returns create new game view
        /// </summary>
        /// <returns>View</returns>
        public ViewResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates new Game from posted form values
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost]
        public ViewResult Create(Game game)
        {
            OperationStatus _opStatus = _service.CreateGame(game.CreatorId, game.Name);
            ViewBag.OperationStatus = _opStatus;
            return View();
        }

        /// <summary>
        /// Returns list of users that you can add to a game 
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        public ViewResult ViewUsers(Game game)
        {
            return View(_service.GetAddUserTeamViewModelForGame(game));
        }


        /// <summary>
        /// Adds selected User to this Game.
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="gameId"></param>
        /// <returns></returns>
        /// <remarks></remarks>
        public ActionResult AddUserToGame(int userId, int gameId)
        {
            _service.AddUserToGame(userId, gameId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Resets a game: deletes all userteams, sets game properties to default
        /// </summary>
        /// <param name="gameId"></param>
        /// <returns>RedirectToAction - Index</returns>
        ///<remarks></remarks>
        public ActionResult ResetGame(int gameId)
        {
            _service.ResetGame(gameId);
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Instantiates game.  Shuffles UserTeams into random order, sets Game properties to 'started'
        /// </summary>
        /// <param name="gameId"></param>
        /// <returns>RedirectToAction - Index</returns>
        /// <remarks></remarks>
        public ActionResult StartGame(int gameId)
        {
            _service.StartGame(gameId);
            return RedirectToAction("Index");
        }

    }
}

IDSM/Controllers/ViewPlayersController.cs
using System.Linq;
using System.Web.UI.WebControls;
using IDSM.Model;
using System.Collections.Generic;
using System.Web.Mvc;
using IDSM.Model.ViewModels;
using IDSM.ServiceLayer;
using IDSM.Signlr;
using Microsoft.AspNet.SignalR;

namespace IDSM.Controllers
{
    [System.Web.Mvc.Authorize]
    public class ViewPlayersController : Controller
    {
        private IService _service;
        //private const int _teamSize = 2;

        public ViewPlayersController(IService service)
        {
            _service = service;
        }

        public ActionResult Index(int? userTeamId, int userId, int gameId, string footballClub, string searchString)
        {
            var _activeTeams = _service.GetAllGamesUserCurrentlyPlaying(userId, userTeamId, footballClub, searchString);
            return View(_activeTeams);
        }

        [HttpPost]
        public ActionResult TeamOverView(int userTeamId, string clubs, string searchString, int gameId)
        {
            if (clubs == null) clubs = "";
            if (searchString == null) searchString = "";

            var _teamOverView = _service.GetTeamOverViewViewModel((int)userTeamId, gameId, clubs, searchString);
            if (Request.IsAjaxRequest())
            {
               
                return PartialView("playerlist", _teamOverView);
            }
            return PartialView("playerlist", _teamOverView);
        }
    }
}

IDSM/Views/GamesAdmin/Create.cshtml
@model IDSM.Model.Game

@{
    ViewBag.Title = "Create";
    var msg = "";
    if(ViewBag.OperationStatus!=null){
        msg = (ViewBag.OperationStatus.Status == true)? "Data Updated": "Error Updating Data";
    }
}

<h2>Create Game</h2>

<h2 style="margin-left:10px;color:White">@msg</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Game</legend>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.CreatorId)
        </div>
        <div class="editor-field">
            @User.Identity.Name
            @Html.EditorFor(model => model.CreatorId)
            @Html.ValidationMessageFor(model => model.CreatorId)
        </div>*@

        <div class="editor-label">
            Creating game as:  @User.Identity.Name
            <input type="hidden" name="CreatorID" value=" @WebSecurity.GetUserId(User.Identity.Name)" />
            @*WebSecurity.CurrentUserId*@
        </div>

        <div class="editor-label">
            @*@Html.LabelFor(model => model.Name)*@
            <label>Name of Game</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IDSM/Views/GamesAdmin/Details.cshtml
@model IDSM.Model.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@*@foreach (var item in Model) {
    *@<tr>
        <td>
            @Html.DisplayFor(model => model.CreatorId)
        </td>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>

        </td>
    </tr>
@*}*@

</table>

IDSM/Views/GamesAdmin/Index.cshtml
@model IDSM.ViewModel.GameViewModel
@using IDSM.Model;
@{
    ViewBag.Title = "Games List";
}

<h2>Games Administration</h2>
<p>
    @ViewBag.ErrorMessage
    @TempData["err"]
</p>
<p>
    @Html.ActionLink("Create New Game", "Create")
</p>
<table>
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.CreatorId)*@
            Creator: @WebSecurity.CurrentUserName
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Name)*@
            Game Name
        </th>
        <th></th>
        <th>Players (green is current player)</th>
        <th></th>
    </tr>

@foreach (var item in Model.Games) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreatorId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if(!item.HasStarted){
                @Html.ActionLink("Add Player", "ViewUsers", item)
            }
        </td>
        <td>
          @*  @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |*@

            @if(item.HasEnded){
                 //NOTE:
                 // instead of foreach here, cuold write a HTML helper extension method (or a method in viewmodel)
                 // see http://stackoverflow.com/questions/1424015/how-do-i-use-a-function-in-my-asp-net-mvc-view
                 // method is tidier, but this loop does less data acces....
               // foreach (var userteam in item.UserTeamsDTO)
                foreach (var userteam in item.UserTeams)
                {    
                    if (userteam.Id == item.WinnerId)
                    {
                        <p>Game Finished!  Winner is @userteam.User.UserName</p>
                    }
                }
            }

            <div class="userteams">

            @{int userTeamCounter = 0;}
            @{//foreach (var userteam in item.UserTeamsDTO)
              }
            @foreach (var userteam in item.UserTeams)
            {
                if (item.HasStarted)
                {
                    if (item.CurrentOrderPosition == userteam.OrderPosition)
                    {
                        @Html.ActionLink(userteam.User.UserName,"Index", "ViewPlayers", new{userTeamId = userteam.Id, userId=userteam.UserId, gameId=userteam.GameId}, new { @class = "currentplayer" });
                       // @Html.ActionLink(userteam.User.UserName, "ManageUserTeam", new { gameid = item.Id, userid = userteam.UserId }, new { @class = "currentplayer" });
                    }
                    else
                    {
                        @Html.ActionLink(userteam.User.UserName, "Index", "ViewPlayers", new{userTeamId = userteam.Id, userId=userteam.UserId, gameId=userteam.GameId},  new { @class = "notcurrentplayer" });
                       // @Html.ActionLink(userteam.User.UserName, "ManageUserTeam", new { gameid = item.Id, userid = userteam.UserId });
                    }
                    //@Html.ActionLink(userteam.User.UserName + "this should 404", "ManageUserTeam", new { gameid = 4000, userid = 54352 });
                }
                else
                {
                    @userteam.User.UserName
                    //if (!(userTeamCounter == item.UserTeamsDTO.Count))
                    if (!(userTeamCounter == item.UserTeams.Count))
                    {
                        <b>,</b>
                    }
                }
                userTeamCounter++;
            }
            
            </div>
           
@*            @Html.ActionLink("Join game as user1", "JoinGame", new { gameid = item.Id, userid=1 }) |
            @Html.ActionLink("Join game as user2", "JoinGame", new { gameid = item.Id, userid=2 }) |
            @Html.ActionLink("Join game as user3", "JoinGame", new { gameid = item.Id, userid=3 })*@
        </td>
        <td>
             @if(item.HasStarted){
                             @Html.ActionLink("Reset Game", "ResetGame", new { gameid = item.Id})
            }
             @if(!item.HasStarted){
                @Html.ActionLink("Start Game", "StartGame", new{gameId = item.Id})
             }
        </td>
    </tr>
}

</table>

IDSM/Views/GamesAdmin/ViewUsers.cshtml
@model IDSM.ViewModel.AddUserTeamViewModel

@{
    ViewBag.Title = "Add UserTeam";
}

<h2>Add player to the game <i> @Model.Game.Name </i></h2>
@*<h2>Username: @Model.GameId</h2>*@

<table>
    <tr>
        <th>
            Player List
        </th>
        <th>
        </th>
    </tr>

@foreach (var item in Model.Users) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Add", "AddUserToGame", new {userId = item.UserId , gameId = Model.Game.Id})
        </td>
    </tr>
}

</table>