IDSM/Controllers/GamesAdminController.cs
using IDSM.Model;
using System.Web.Mvc;
﻿using IDSM.Repository;
﻿using IDSM.ViewModel;
using IDSM.ServiceLayer;
using WebMatrix.WebData;

namespace IDSM.Controllers
{
    [Authorize]
    public class GamesAdminController : Controller
    {
        //IWebSecurityWrapper _wr;
        private readonly IService _service;

        /// <summary>
        /// Instantiates controller class. Service layer injected by Unity.
        /// </summary>
        /// <param name="service"></param>
        public GamesAdminController(IService service)
        {
            _service = service;
        }

        /// <summary>
        /// Displays 'Games Homepage' view - list of all active games, plus navigation to create new games & reset games 
        /// </summary>
        /// <returns></returns>
        public ViewResult Index()
        {
           // GameViewModel _gvm = new GameViewModel { Games = _service.GetAllGames() };
            GameViewModel _gvm = new GameViewModel { Games = _service.GetAllGamesUserParticipatesIn(WebSecurity.CurrentUserId) };
            return View(_gvm);
        }

        /// <summary>
        /// Returns create new game view
        /// </summary>
        /// <returns>View</returns>
        public ViewResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates new Game from posted form values
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost]
        public ViewResult Create(Game game)
        {
            OperationStatus _opStatus = _service.CreateGame(game.CreatorId, game.Name);
            ViewBag.OperationStatus = _opStatus;
            return View();
        }

        /// <summary>
        /// Returns list of users that you can add to a game 
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        public ViewResult ViewUsers(Game game)
        {
            return View(_service.GetAddUserTeamViewModelForGame(game));
        }


        /// <summary>
        /// Adds selected User to this Game.
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="gameId"></param>
        /// <returns></returns>
        /// <remarks></remarks>
        public ActionResult AddUserToGame(int userId, int gameId)
        {
            _service.AddUserToGame(userId, gameId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Resets a game: deletes all userteams, sets game properties to default
        /// </summary>
        /// <param name="gameId"></param>
        /// <returns>RedirectToAction - Index</returns>
        ///<remarks></remarks>
        public ActionResult ResetGame(int gameId)
        {
            _service.ResetGame(gameId);
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Instantiates game.  Shuffles UserTeams into random order, sets Game properties to 'started'
        /// </summary>
        /// <param name="gameId"></param>
        /// <returns>RedirectToAction - Index</returns>
        /// <remarks></remarks>
        public ActionResult StartGame(int gameId)
        {
            _service.StartGame(gameId);
            return RedirectToAction("Index");
        }

    }
}

IDSM/Controllers/GamesController.cs
using IDSM.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcPaging;
using IDSM.Logging.Services.Logging.Log4Net;
using WebMatrix.WebData;
using IDSM.Wrapper;
using IDSM.ViewModel;
using IDSM.Helpers;
using IDSM.Exceptions;
using IDSM.Logging.Services.Logging;
using AutoMapper;
using IDSM.ServiceLayer;


namespace IDSM.Controllers
{
     [Authorize]
    public class GamesController : Controller
    {
         private IService _service;

          public GamesController(IService service)
        {
            _service = service;
        }

          /// <summary>
          /// Index
          /// </summary>
          /// <returns></returns>
          public ViewResult Index()
          {
              return View();
          }

    }
}

IDSM/Views/Shared/_AdminPartial.cshtml
@if (Request.IsAuthenticated && User.Identity.Name == "jamie_admin") {
       <ul style="display:inline; border:1px solid black; padding:0px; list-style:none;margin:0px;"><li style="border:1px solid black;padding:0px;margin:0px; list-style:none;">@Html.ActionLink("Upload", "Upload", "Home")</li></ul>
}

IDSM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/jquery-2.1.0.js"></script>
        <script src="~/Scripts/jquery-ui-1.11.1.js"></script>
        @*<script src="~/Scripts/jquery.ui.dialog.js"></script>*@


        @Scripts.Render("~/bundles/jqueryval")

  <link rel="stylesheet" href="/resources/demos/style.css" />
  
    </head>
    <body>
        

        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("International Dream Soccer Manager", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                          @*  <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                             @Html.Partial("_LoggedInPartial")
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - International Dream Soccer Manager</p>
                </div>
            </div>
        </footer>

     @*   @Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", required: false)
    </body>
</html>

IDSM/Views/Shared/_LoggedInPartial.cshtml
@if (Request.IsAuthenticated) {
    <!--<li>@Html.ActionLink("Games Home", "Index", "Games")</li>-->
    <li>@Html.ActionLink("Games", "Index", "GamesAdmin")</li>
}